# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_create = QtWidgets.QPushButton(self.centralwidget)
        self.button_create.setGeometry(QtCore.QRect(10, 10, 80, 25))
        self.button_create.setDefault(False)
        self.button_create.setFlat(False)
        self.button_create.setObjectName("button_create")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(100, 10, 80, 25))
        self.button_add.setObjectName("button_add")
        self.button_unpack = QtWidgets.QPushButton(self.centralwidget)
        self.button_unpack.setGeometry(QtCore.QRect(190, 10, 101, 25))
        self.button_unpack.setToolTip("")
        self.button_unpack.setObjectName("button_unpack")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(20, 50, 481, 17))
        self.label_info.setText("Текущий файл")
        self.label_info.setObjectName("label_info")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 491, 211))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.button_unpack_all = QtWidgets.QPushButton(self.centralwidget)
        self.button_unpack_all.setGeometry(QtCore.QRect(300, 10, 121, 25))
        self.button_unpack_all.setObjectName("button_unpack_all")
        self.button_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_close.setGeometry(QtCore.QRect(430, 10, 89, 25))
        self.button_close.setObjectName("button_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.create_archive = QtWidgets.QAction(MainWindow)
        self.create_archive.setObjectName("create_archive")
        self.open_archive = QtWidgets.QAction(MainWindow)
        self.open_archive.setObjectName("open_archive")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.menu.addAction(self.create_archive)
        self.menu.addAction(self.open_archive)
        self.menu.addAction(self.Exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АрхивариусЪ"))
        self.button_create.setText(_translate("MainWindow", "Сохранить"))
        self.button_add.setText(_translate("MainWindow", "Добавить"))
        self.button_unpack.setText(_translate("MainWindow", "Распаковать"))
        self.button_unpack_all.setText(_translate("MainWindow", "Распаковать всё"))
        self.button_close.setText(_translate("MainWindow", "Закрыть"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.create_archive.setText(_translate("MainWindow", "Создать"))
        self.create_archive.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.open_archive.setText(_translate("MainWindow", "Открыть"))
        self.open_archive.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.Exit.setText(_translate("MainWindow", "Выход"))
        self.Exit.setShortcut(_translate("MainWindow", "Alt+X"))
